export const ROUTE = Object.freeze({
	HOME: 'Home',
	ADMIN: 'Admin',
	PROFILE: 'Profile',
	DATA_EXPORT: 'DataExport',
	DATA_REVIEW: 'DataReview',
	DATA_UPLOAD: 'DataUpload',
	DATA_VIEW: 'DataView',
	FEEDBACK_VIEW: 'FeedbackView',
	ONTOLOGY_VIEW: 'OntologyView',
	ONTOLOGY_REVIEW: 'OntologyReview',
	ONTOLOGY_UPLOAD: 'OntologyUpload',
	LEGAL_NOTICE: 'LegalNotice',
	PASSWORD_RESET: 'PasswordReset',
	NOT_FOUND: 'NotFound',
});

export const TOAST_TYPE = Object.freeze({
	INFO: 'INFO',
	SUCCESS: 'SUCCESS',
	WARN: 'WARN',
	ERROR: 'ERROR',
});

export const REQUEST_STATUS = Object.freeze({
	// 2xx Success
	OK: 200,
	CREATED: 201,
	ACCEPTED: 202,
	NO_CONTENT: 204,

	// 3xx Redirection
	MOVED_PERMANENTLY: 301,
	FOUND: 302,
	NOT_MODIFIED: 304,
	TEMPORARY_REDIRECT: 307,
	PERMANENT_REDIRECT: 308,

	// 4xx Client Errors
	BAD_REQUEST: 400,
	UNAUTHORIZED: 401,
	FORBIDDEN: 403,
	NOT_FOUND: 404,
	METHOD_NOT_ALLOWED: 405,
	REQUEST_TIMEOUT: 408,
	CONFLICT: 409,
	GONE: 410,
	UNPROCESSABLE_ENTITY: 422,
	TOO_MANY_REQUESTS: 429,

	// 5xx Server Errors
	INTERNAL_SERVER_ERROR: 500,
	NOT_IMPLEMENTED: 501,
	BAD_GATEWAY: 502,
	SERVICE_UNAVAILABLE: 503,
	GATEWAY_TIMEOUT: 504,
});

export const MSG_TYPE = Object.freeze({
	UNAUTHORIZED: 'UNAUTHORIZED',
	FORBIDDEN: 'FORBIDDEN',
	REGISTRATION_SUCCESS: 'REGISTRATION_SUCCESS',
	LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
});

export const GENDER = Object.freeze({
	MALE: 'MALE',
	FEMALE: 'FEMALE',
	OTHER: 'OTHER',
});

export const ROLE = Object.freeze({
	ADMIN: 'ADMIN',
	SUPER_ADMIN: 'SUPER_ADMIN',
	PRACTITIONER: 'PRACTITIONER',
	RESEARCHER: 'RESEARCHER',
	MAINTAINER: 'MAINTAINER',
});

export const PERMISSION = Object.freeze({
	ONTOLOGY_VIEW: 'ONTOLOGY_VIEW',
	ONTOLOGY_UPLOAD: 'ONTOLOGY_UPLOAD',
	ONTOLOGY_REVIEW: 'ONTOLOGY_REVIEW',
	ONTOLOGY_EXPORT: 'ONTOLOGY_EXPORT',
	DATA_UPLOAD: 'DATA_UPLOAD',
	DATA_VIEW: 'DATA_VIEW',
	DATA_EXPORT: 'DATA_EXPORT',
	DATA_REVIEW: 'DATA_REVIEW',
	ADMIN: 'ADMIN',
	SUPER_ADMIN: 'SUPER_ADMIN',
});

export const VERIFICATION_STATUS = Object.freeze({
	VERIFIED: 'VERIFIED',
	NOT_VERIFIED: 'NOT_VERIFIED',
	CODE_EXPIRED: 'CODE_EXPIRED',
});

export const STUDY_PURPOSE = Object.freeze({
	FEASIBILITY_CHECK: 'FEASIBILITY_CHECK',
	PILOT_STUDY: 'PILOT_STUDY',
	DATA_ANALYSIS: 'DATA_ANALYSIS',
	DATA_COLLECTION: 'DATA_COLLECTION',
	INTERVENTION_RESEARCH: 'INTERVENTION_RESEARCH',
});

export const SORT_ORDER = Object.freeze({
	ASC: 'ASC',
	DESC: 'DESC',
});

export const GRAPH_TYPE = Object.freeze({
	ONTOLOGY: 'ONTOLOGY',
	DATA: 'DATA',
});

export const ONTOLOGY_ELEMENT = Object.freeze({
	STAKEHOLDER: 'STAKEHOLDER',
	NODE: 'NODE',
	LEAF: 'LEAF',
	RELATIONSHIP: 'RELATIONSHIP',
	DATA: 'DATA',
});

export const ONTOLOGY_OPERATION = Object.freeze({
	ADDED: 'ADDED',
	MODIFIED: 'MODIFIED',
	DELETED: 'DELETED',
	UNMODIFIED: 'UNMODIFIED',
});

export const REVIEW_STATUS = Object.freeze({
	ACCEPTED: 'ACCEPTED',
	DECLINED: 'DECLINED',
	MODIFICATION_NEEDED: 'MODIFICATION_NEEDED',
	ASSIGNED: 'ASSIGNED',
	OPEN: 'OPEN',
});

export const MIGRAION_OPERATION = Object.freeze({
	LINKING: 'LINKING',
	UNLINKING: 'UNLINKING',
	RELINKING: 'RELINKING',
	ATTRIBUTE_MODIFICATION: 'ATTRIBUTE_MODIFICATION',
	CREATION: 'CREATION',
	ADDITION: 'ADDITION',
	INSERTION_SINGLE: 'INSERTION_SINGLE',
	INSERTION_MULTIPLE: 'INSERTION_MULTIPLE',
	EXTENSION: 'EXTENSION',
	DELETION: 'DELETION',
	DELETION_PARTIAL: 'DELETION_PARTIAL',
	DELETION_FULL: 'DELETION_FULL',
	DELETION_LEAF: 'DELETION_LEAF',
});

export const TABLE_SELECTION = Object.freeze({
	ROW_SELECT: 'ROW_SELECT',
	COLUMN_SELECT: 'COLUMN_SELECT',
	DISABLED: 'DISABLED',
});

export const TABLE_SELECTION_AMOUNT = Object.freeze({
	SINGLE: 'SINGLE',
	MULTIPLE: 'MULTIPLE',
});

export const FILE_TYPE = Object.freeze({
	CSV: 'CSV',
	XLSX: 'XLSX',
	JSON: 'JSON',
});

export const UPLOAD_TYP = Object.freeze({
	UPLOAD_DATA: 'UPLOAD_DATA',
	UPLOAD_ONTOLOGY: 'UPLOAD_ONTOLOGY',
});

export const DATA_QUALITY_CHECK_MODE = Object.freeze({
	UPLOAD: 'UPLOAD',
	VIEW: 'VIEW',
});

export const QUALITY_CHECK_METHOD = Object.freeze({
	VALUE_TYPE: 'VALUE_TYPE',
	VALUE_RANGE_MIN: 'VALUE_RANGE_MIN',
	VALUE_RANGE_MAX: 'VALUE_RANGE_MAX',
	VALUE_MAPPING: 'VALUE_MAPPING',
	// VALUE_BRANCHING: 'VALUE_BRANCHING',
	VALUE_REQUIRED: 'VALUE_REQUIRED',
	EMPTY_ROWS: 'EMPTY_ROWS',
	EMPTY_COLUMNS: 'EMPTY_COLUMNS',
	EMPTY_VALUES: 'EMPTY_VALUES',
});

export const MAPPING_SPLIT = Object.freeze({
	COMMA: 'COMMA',
	SEMICOLON: 'SEMICOLON',
	DASH: 'DASH',
	UNDERSCORE: 'UNDERSCORE',
	SLASH: 'SLASH',
	COLON: 'COLON',
	DOT: 'DOT',
	BAR: 'BAR',
});

export const BRANCHING_FORMAT = Object.freeze({
	ONLY_NUMBER: 'ONLY_NUMBER',
	ONLY_STRING: 'ONLY_STRING',
	FULL_STRING: 'FULL_STRING',
});
