# Generated by Django 5.1.5 on 2025-04-18 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('columns', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='CodeBookRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cells', models.JSONField()),
                ('assigned_item_id', models.IntegerField(blank=True, null=True)),
                ('codebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='study.codebook')),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.TextField()),
                ('purpose', models.CharField(choices=[('FEASIBILITY_CHECK', 'FEASIBILITY_CHECK'), ('PILOT_STUDY', 'PILOT_STUDY'), ('DATA_ANALYSIS', 'DATA_ANALYSIS'), ('DATA_COLLECTION', 'DATA_COLLECTION'), ('INTERVENTION_RESEARCH', 'INTERVENTION_RESEARCH')], max_length=50)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('drks_id', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_studies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='codebook',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codebooks', to='study.study'),
        ),
    ]
