# Generated by Django 5.1.5 on 2025-04-22 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codebook',
            name='columns',
        ),
        migrations.CreateModel(
            name='CodeBookColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.TextField()),
                ('assigned_meta_tag', models.CharField(blank=True, max_length=255, null=True)),
                ('codebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='study.codebook')),
            ],
        ),
    ]
