# Generated by Django 5.1.5 on 2025-04-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_alter_codebookcolumn_options_codebookcolumn_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codebookrow',
            name='assigned_item_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
