# Generated by Django 5.1.5 on 2025-04-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_alter_codebookrow_assigned_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='codebookrow',
            name='row_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
