# Generated by Django 5.1.5 on 2025-04-05 20:38

import django.db.models.deletion
import reviewer.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('submission_date', models.DateTimeField()),
                ('submission_status', models.CharField(choices=[('STATUS_OPEN', 'OPEN'), ('STATUS_ASSIGNED', 'ASSIGNED'), ('STATUS_MODIFICATION_NEEDED', 'MODIFICATION_NEEDED'), ('STATUS_DECLINED', 'DECLINED'), ('STATUS_ACCEPTED', 'ACCEPTED')], default=reviewer.models.StatusChoices['STATUS_OPEN'], max_length=30)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reviews', to=settings.AUTH_USER_MODEL)),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
