# Generated by Django 5.1.5 on 2025-04-08 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='submission_status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('ASSIGNED', 'Assigned'), ('MODIFICATION_NEEDED', 'Modification Needed'), ('DECLINED', 'Declined'), ('ACCEPTED', 'Accepted')], default='OPEN', max_length=30),
        ),
        migrations.CreateModel(
            name='ReviewDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('review_status', models.CharField(blank=True, choices=[('MODIFICATION_NEEDED', 'Modification Needed'), ('DECLINED', 'Declined'), ('ACCEPTED', 'Accepted')], max_length=20, null=True)),
                ('review_comment', models.TextField(blank=True, null=True)),
                ('reviewer_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='reviewer.review')),
            ],
        ),
    ]
