# Generated by Django 5.1.5 on 2025-04-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0002_alter_review_submission_status_reviewdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='upload_type',
            field=models.CharField(choices=[('UPLOAD_DATA', 'Upload Data'), ('UPLOAD_ONTOLOGY', 'Upload Ontology')], default='UPLOAD_ONTOLOGY', max_length=30),
        ),
    ]
