# Generated by Django 5.1.5 on 2025-04-18 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0004_review_study_alter_reviewdetails_review_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewdetails',
            old_name='review_comment',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='reviewdetails',
            old_name='review_status',
            new_name='status',
        ),
    ]
