# Generated by Django 5.1.5 on 2025-04-22 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0005_rename_review_comment_reviewdetails_comment_and_more'),
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewdetails',
            name='modified_ontology',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='study.study'),
        ),
    ]
