# Generated by Django 5.1.5 on 2025-04-23 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0006_feedback'),
        ('reviewer', '0006_reviewdetails_modified_ontology_alter_review_study'),
    ]

    operations = [
    ]
