# Generated by Django 5.1.5 on 2025-04-24 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0007_merge_20250423_1226'),
        ('study', '0003_alter_codebookcolumn_options_codebookcolumn_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='study.study'),
        ),
    ]
