# Generated by Django 5.1.5 on 2025-04-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0008_alter_review_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewdetails',
            name='modified_ontology',
            field=models.CharField(blank=True, max_length=10000000, null=True),
        ),
    ]
