# Generated by Django 5.1.5 on 2025-04-25 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0009_alter_reviewdetails_modified_ontology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewdetails',
            name='modified_ontology',
            field=models.TextField(blank=True, null=True),
        ),
    ]
