# Generated by Django 5.1.5 on 2025-03-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scope',
            name='name',
            field=models.CharField(choices=[('SUPER_ADMIN', 'SUPER_ADMIN'), ('ADMIN', 'ADMIN'), ('DATA_EXPORT', 'DATA_EXPORT'), ('DATA_REVIEW', 'DATA_REVIEW'), ('DATA_UPLOAD', 'DATA_UPLOAD'), ('DATA_VIEW', 'DATA_VIEW'), ('ONTOLOGY_EXPORT', 'ONTOLOGY_EXPORT'), ('ONTOLOGY_REVIEW', 'ONTOLOGY_REVIEW'), ('ONTOLOGY_UPLOAD', 'ONTOLOGY_UPLOAD'), ('ONTOLOGY_VIEW', 'ONTOLOGY_VIEW')], max_length=50, unique=True),
        ),
    ]
