# Generated by Django 5.1.5 on 2025-04-24 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph_migrations', '0001_initial'),
        ('reviewer', '0007_merge_20250423_1226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='graphmigrationsettings',
            options={'ordering': ['review_details', 'index']},
        ),
        migrations.AddField(
            model_name='graphmigrationsettings',
            name='index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='graphmigrationsettings',
            name='review_details',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='migrations', to='reviewer.reviewdetails'),
            preserve_default=False,
        ),
    ]
